import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[shell]
program = "/opt/homebrew/bin/zsh"
args = ["-l", "-c", "tmux"]

[font]
size = 25

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 0.9

[window.padding]
x = 7
y = 0
