unbind C-a
set-option -g prefix C-b
bind-key C-b send-prefix

bind r source-file ~/.tmux.conf

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set-option -g history-limit 25000

# for neovim
set -sg escape-time 10

# vi for copy mode
setw -g mode-keys vi

# status bar
set -g status-right "#(pomo)"
set -g status-style "fg=#665c54"
set -g status-left-style "fg=#928374"

set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left ""


# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# https://michenriksen.com/posts/italic-text-in-alacritty-tmux-neovim/
set -g default-terminal "alacritty"
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # colored underscores
set -as terminal-overrides ',alacritty:RGB' # true-color support

################### ################### ###################


# vim-like pane resizing
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# vim-like pane switching
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# last session
bind p switch-client -l

set-option -g default-shell /opt/homebrew/bin/zsh
bind-key -r F run-shell "tmux neww ~/Repos/github.com/g-e-e-z/dotfiles/scripts/tmux-sessionizer"
