#!/bin/bash

# XDG
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p ~/Repos

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install --cask alacritty
brew install --cask font-ubuntu-mono-nerd-font
brew install --cask hammerspoon
# brew install --cask docker # May not work, update next time
# brew install --cask obsidian
# brew install --cask darktable
# brew install --cask gimp
brew install tmux fzf neovim newsboat kubectl rg gsed jq jd coreutils httpie \
    lazygit lazydocker tree node go pure zsh-syntax-highlighting \
    docker-completion libpq cmake luarocks

# TODO: Migrate away from packer to lazy:
# Install packer
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
# Tmux package manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Symbolic links files
ln -sf "$PWD/.zprofile" "$HOME/.zprofile"
ln -sf "$PWD/.zshrc" "$HOME/.zshrc"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"

# Symbolic links dirs
ln -sf "$PWD/Backgrounds" "$HOME/Pictures"
ln -sf "$PWD/alacritty" "$XDG_CONFIG_HOME"
ln -sf "$PWD/k9s" "$XDG_CONFIG_HOME"
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"
ln -sf "$PWD/.newsboat" "$HOME"
ln -sf "$PWD/.hammerspoon" "$HOME"
