#!/bin/bash
# Change shell to bash
chsh -s /bin/bash

# XDG compliance
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/alacritty
mkdir -p "$XDG_CONFIG_HOME"/k9s
mkdir -p ~/Repos
mkdir -p "$HOME"/.newsboat/config
mkdir -p "$HOME"/.newsboat/urls

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Required commands for brew
(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/alexgordon/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install --cask alacritty
brew install --cask font-ubuntu-mono-nerd-font
brew install --cask docker # May not work, update next time
# brew install --cask obsidian
brew install tmux fzf neovim bash-completion@2 newsboat kubectl rg gsed jq jd coreutils httpie lazygit lazydocker tree node go

# TODO: Migrate away from packer:
# Install packer
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

#  set up git prompt
curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh >"$XDG_CONFIG_HOME"/bash/git-prompt.sh
# Git branch auto completion
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash

# Setup alacritty themes
mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
cp -a "$PWD/alacritty_themes/." "$XDG_CONFIG_HOME"/alacritty/themes

# Symbolic links
ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml
ln -sf "$PWD/k9s/skin.yml" "$XDG_CONFIG_HOME"/k9s/skin.yml
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"
ln -sf "$PWD/newsboat/config" "$HOME"/.newsboat/config
ln -sf "$PWD/newsboat/urls" "$HOME"/.newsboat/urls
