set -ga terminal-overrides ",xterm-256color*:Tc"
# Try this if colors are weird
# set-option -as terminal-overrides ",xterm*:RGB"
set -s escape-time 0
set -g default-terminal "tmux-256color"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf
set -g base-index 1
set -g pane-base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane resizing
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# vim-like pane switching
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# last session
bind p switch-client -l


# and now unbind keys
unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/.dotfiles/code/todo.md"

bind-key -r F run-shell "tmux neww ~/bin/tmux-sessionizer.sh"


# Colors
set-option -g status-style bg=colour237,fg=colour223 # bg=bg1, fg=fg1
set-option -g pane-active-border-style fg=colour250 #fg2
set-option -g pane-border-style fg=colour237 #bg1
