-- NOTE: lazy.nvim(Plugin Manager) options
return {
	-- defaults = { lazy = true },
	-- install = { colorscheme = { "nvchad" } },
	-- automatically check for plugin updates
	checker = { enabled = true },
	change_detection = {
		-- automatically check for config file changes and reload the ui
		enabled = false,
		notify = false, -- get a notification when changes are found
	},
	lockfile = vim.fn.stdpath("data") .. "/lazy-lock.json",
	-- diff = {
	--   cmd = "diffview.nvim",
	-- },
	ui = {
		border = vim.g.border_enabled and "rounded" or "none",
		icons = vim.g.have_nerd_font and {} or {
			-- ft = "",
			-- lazy = "󰂠 ",
			loaded = "",
			not_loaded = "",
			cmd = "⌘",
			config = "🛠",
			event = "📅",
			ft = "📂",
			init = "⚙",
			keys = "🗝",
			plugin = "🔌",
			runtime = "💻",
			require = "🌙",
			source = "📄",
			start = "🚀",
			task = "📌",
			lazy = "💤 ",
		},
	},
	performance = {
		rtp = {
			disabled_plugins = {
				"2html_plugin",
				"tohtml",
				"getscript",
				"getscriptPlugin",
				"gzip",
				"logipat",
				"netrw",
				"netrwPlugin",
				"netrwSettings",
				"netrwFileHandlers",
				"matchit",
				"tar",
				"tarPlugin",
				"rrhelper",
				"spellfile_plugin",
				"vimball",
				"vimballPlugin",
				"zip",
				"zipPlugin",
				"tutor",
				"rplugin",
				"syntax",
				"synmenu",
				"optwin",
				"compiler",
				"bugreport",
				"ftplugin",
			},
		},
	},
}
