format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "fg:#b8bb26" # Gruvbox green

[character]
success_symbol = "[❯](fg:#fabd2f)"     # Gruvbox yellow
error_symbol = "[❯](fg:#fb4934)"       # Gruvbox red
vimcmd_symbol = "[❮](fg:#83a598)"      # Gruvbox blue
[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "fg:#d3869b"  # Gruvbox purple
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "fg:#fe8019" # Gruvbox orange

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
