#!/bin/bash

# --- Setup ---
today=$(date +"%Y-%m-%d")

TARGET_DIR="$SECOND_BRAIN/periodic-notes/daily-notes/"
daily_dir=$TARGET_DIR

last_file=$(ls "$daily_dir" | tail -n 1)
last_date=${last_file%.*}
file="$daily_dir${today}.md"

cd "$TARGET_DIR" || exit

# --- Template Generator ---
new_note() {
  touch "$file"

  cat <<EOF >"$file"
---
date: ${today}
tags:
  - daily
urls:
  -
---

[[$last_date]] - [_placeholder_]

# $(date +"%B %d, %Y")

## Log

## Standup / Planning (9:00-9:30)

- Primary Objective:
- [ ]
- Secondary Objectives:
- [ ]
- [ ]

## Shutdown (4:30–5:00)

- Reconciliation:
- [ ] SB Inbox
- [ ] Update Task Status

- Timeblock Next Workday

- Close Laptop

## Notes

EOF
}

# --- Create New File If Missing ---
if [ ! -f "$file" ]; then
  echo "Creating new daily engineering note for $today."
  gsed -i "s/_placeholder_/[$today]/" "$daily_dir$last_file"
  new_note
fi

# --- Open File in Neovim ---
nvim "+ normal gg" "$file"
