#!/bin/bash

# --- Setup ---
today=$(date +"%Y-%m-%d")

TARGET_DIR="$SECOND_BRAIN/periodic-notes/daily-notes/"
daily_dir=$TARGET_DIR

last_file=$(ls "$daily_dir" | tail -n 1)
last_date=${last_file%.*}
file="$daily_dir${today}.md"

cd "$TARGET_DIR" || exit

# --- Template Generator ---
new_note() {
  touch "$file"

  cat <<EOF >"$file"
---
date: ${today}
tags:
  - daily
urls:
  -
---

[[$last_date]] - [_placeholder_]

# $(date +"%B %d, %Y")

## Standup / Planning
- Top 2 priorities:
- [ ]
- [ ]
- Blockers:
- [ ]
- Notes:
-

## Deep Work Block #1 (10:00–12:00)
- [ ] Focus goal:
- [ ] Notes or insights:
- [ ] Next small step:

## Gym / Lunch (12:00–1:30)

## Deep Work Block #2 (1:30–3:30)
- [ ] Focus goal:
- [ ] Notes or insights:
- [ ] Next small step:

## Collaboration & Reviews (3:30–4:30)
- [ ] PRs or design docs reviewed:
- [ ] Knowledge shared or documented:

## Shutdown (4:30–5:00)
- [ ] What moved forward today:
- [ ] Recurring blockers:
- [ ] Tomorrow’s top 2 priorities:
- [ ]
- [ ]

## Reflections
- Technical concept I learned:
- What went well:
- What to improve:
EOF
}

# --- Create New File If Missing ---
if [ ! -f "$file" ]; then
  echo "Creating new daily engineering note for $today."
  gsed -i "s/_placeholder_/[$today]/" "$daily_dir$last_file"
  new_note
fi

# --- Open File in Neovim ---
nvim "+ normal gg" "$file"
