#!/bin/bash
s="$_"
query=

case "$1" in
    '')   ;;
    that) query="search?q=${s//[[:space:]]/+}" ;;
    *)    s="$*"; query="search?q=${s//[[:space:]]/+}" ;;
esac

open /Applications/Google Chrome.app/ "http://www.google.com/${query}"
