#!/bin/bash

ALAC="$DOTFILES/alacritty.toml"
VIMD="$DOTFILES/nvim/after/plugin/colors.lua"
PICS="~/Pictures/Backgrounds"

clear
echo "******* Click! *******"
if [[ $(grep "light" $ALAC) ]]; then
    gsed -i "s|light|dark|" $ALAC
    gsed -i "s|light|dark|" $VIMD
    osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"${PICS}/gruvbox-dark.png\" as POSIX file"
    osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'

    echo "            "
    echo "           _    "
    echo "          (~)    "
    echo "           #    "
    echo ""
else
    gsed -i "s|dark|light|" $ALAC
    gsed -i "s|dark|light|" $VIMD
    osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"${PICS}/gruvbox-light.png\" as POSIX file"
    osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to false'
    echo "           :"
    echo "       '.  _  .'"
    echo "      -=  (~)  =-"
    echo "       .'  #  '."
    echo ""
fi


# set_wallpaper(){
#     osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"${1}\" as POSIX file"
# }
#
# case $1 in
#     help)
#         help
#         ;;
#     *)
#         [ -z "$1" ] && help && exit 1
#         set_wallpaper "$1"
#         shift
#         ;;
# esac
