#!/bin/bash

mkdir -p "$SECOND_BRAIN"/0-inbox
mkdir -p "$SECOND_BRAIN"/1-project
mkdir -p "$SECOND_BRAIN"/2-areas
mkdir -p "$SECOND_BRAIN"/3-resources
mkdir -p "$SECOND_BRAIN"/4-archive
mkdir -p "$SECOND_BRAIN"/periodic-notes
mkdir -p "$SECOND_BRAIN"/periodic-notes/daily-notes
