#!/bin/bash
# function to prompt the user for a filename
get_filename() {
	read -p "Enter a filename: " filename
	echo "$filename"
}
# function to create and open a file in the specified directory
open_file() {

	# Cd into the directory
	cd "$1" || exit
	# Create the file in the specified directory
	touch "$1/$filename.md"

	# create unique identifier and links section
	timestamp="$(date +"%Y%m%d%H%m")"
	# format the file
	{
		echo "---"
		echo "id: $timestamp"
        echo "date: $(date +"%Y-%m-%d")"
		echo "hubs:"
		echo "    -"
		echo "tags:"
		echo "    -"
		echo "urls:"
		echo "    -"
		echo "---"
	} >>"$1/$filename.md"

	# Open the file in Neovim
	nvim '+ normal ggzzi' "$1/$filename.md"
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
    raw_filename=$(get_filename)
    filename=$(echo $raw_filename | tr " " "_")
fi

# set filename to the argument formatted arg
if [[ $# -eq 1 ]]; then
	filename=$1
fi

open_file "$SECOND_BRAIN/0-inbox/"
