#!/bin/bash

ALAC="$DOTFILES/alacritty.toml"
K9S="$DOTFILES/k9s/config.yml"
VIMD="$DOTFILES/nvim/after/plugin/colors.lua"
BG_DIR="Users/$USER/Pictures/Backgrounds"
LIGHT_FILE="gruvbox-light.png"
DARK_FILE="gruvbox-dark.png"

clear

MODE=$(defaults read -g AppleInterfaceStyle 2>/dev/null)

if [[ $MODE == "Dark" ]]; then
    # Switch to light
    gsed -i "s|dark|light|" $ALAC
    gsed -i "s|dark|light|" $VIMD
    gsed -i "s|dark|light|" $K9S
    FILE=$LIGHT_FILE
else
    # Switch to dark
    gsed -i "s|light|dark|" $ALAC
    gsed -i "s|light|dark|" $VIMD
    gsed -i "s|light|dark|" $K9S
    FILE=$DARK_FILE
fi

/usr/libexec/PlistBuddy -c "set AllSpacesAndDisplays:Desktop:Content:Choices:0:Files:0:relative file:///$BG_DIR/$FILE" ~/Library/Application\ Support/com.apple.wallpaper/Store/Index.plist && \
killall WallpaperAgent
osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to not dark mode'
