#!/usr/bin/env bash
# Copied from the primeagen
if [[ $# -eq 1 ]]; then
    selected=$1
else
    repos=$(find ~/Repos/github.com/* ~/notes -mindepth 1 -maxdepth 1 -type d)
    selected=$(
        echo "$repos" | \
        # Note: defaults are not copied to new tmux shell, copy and pasted colors from bashrc
        fzf --color=fg+:-1,bg+:-1,bg:-1,hl+:#cc241d,hl:#fb4934,prompt:#fb4934,pointer:#fb4934,spinner:#fb4934 \
            --tmux 90% --reverse --preview 'tree -CL 2 {} | head -200' \
            --preview-window=right:45% --prompt="Select a directory: ")
fi

if [[ -z $selected ]]; then
    exit 0
fi
echo $selected

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
