set -ga terminal-overrides ",xterm-256color*:Tc"
# Try this if colors are weird
# set-option -as terminal-overrides ",xterm*:RGB"
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'


# vim-like pane switching
bind ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/.dotfiles/personal/todo.md"

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-windowizer.sh"
bind-key -r F run-shell "tmux neww ~/.local/bin/tmux-sessionizer.sh"

bind-key -r i run-shell "tmux neww ~/.local/bin/tmux-cht.sh"
bind-key -r H run-shell "~/.local/bin/tmux-sessionizer.sh ~/personal/neotes"

###### Color scheme ######
# monitor window changes
set-option -wg monitor-activity on
set-option -wg monitor-bell on

# set statusbar update interval
set-option -g status-interval 1

# "#fe8019" MUST be in lowercase here (conflicts with statusline alias otherwise)
set-option -g status-style bg=terminal,fg="#A89984"
set-option -g status-left "#[bg=#24283b, fg=#24283b]#{?client_prefix,#[bg=#7aa2f7],#[bg=#3d59a1]} #{session_name} "
set-option -g status-right '#[bg=terminal, fg=#7C6F64]#(exec tmux ls|cut -d " " -f 1|tr ":", " "|tr " " ","|xargs echo 'sessions:'|rev|cut -c2-|rev ) | %Y-%m-%d %H:%M:%S #[bg=#A89984, fg=#24283b]#{?client_prefix,#[bg=#7aa2f7],#[bg=#3d59a1]} #{host_short} '
set -g status-left-length 100
set -g status-right-length 100

set-option -wg window-status-current-format "#{?window_zoomed_flag,#[fg=default bold],#[fg=default]} #{window_index} #{window_name} "
set-option -wg window-status-format "#{?window_zoomed_flag,#[fg=default bold],#[fg=default]} #{window_index} #{window_name} "

